### DISCUSSION TITLE
Use NexGen Editor In Theme Module

### DISCUSSION THREAD

**Discussion by rcampbellDovico** [getgrav/grav-premium-issues#162] [Q&A] [answered]
I am working on creating modules for my Grav theme. My company has purchased the NexGen Content Editor Plugin and I would like to use this as an form input type. So here is an example of an input I’d like to convert to the NextGen Content Editor in my module blueprint YAML file:
```
fields:
            header.header_background_text:
              type: text
              label: 'Page Text'
              help: 'Optional, For if you want bold text at the top of the page'
```
As you can see My input type is set to `type: text` But I want to know the proper value to change text to in order to make it a next gen editor field. Such as: `type: WYSIWYG` or `type: nextgen`

I asked the same question in the Grav Discourse Form and got directed here
https://discourse.getgrav.org/t/use-nexgen-editor-in-theme-module/18507/5
