### ISSUE TITLE
[typhoon] One Page modular menu not working

### ISSUE THREAD

**Issue by danjames68** [getgrav/grav-premium-issues#131]
I've made a one-page website with Typhoon, based on the one-page skeleton. I can't make the menu work. 

In `modular.md` I've set `onpage_menu = true` -  I haven't touched `navigation` or `macro` templates. I started by making a new theme from Typhoon and if I revert back to Typhoon the menu re-appears but just as a page menu - i.e. showing the 'typography' and 'start here' page links.

I've built a few grav sites before, and this is my second or third with Typhoon - but I'm stumped. I've run `npm update` and `npm ci` to check all the packages are there.

This is the header of modular.md:

```
---
title: 'Property Management in Tuscany'
onpage_menu: true
header_bar:
    background: transparent
    text: light
content:
    items: self@.modular
---
```

Any ideas welcome. I'm stumped.
