### ISSUE TITLE
[typhoon] Contact form redirection in Modular page

### ISSUE THREAD

**Issue by rfvallina** [getgrav/grav-premium-issues#178]
Hello,
I have installed theme **typhoon**.
I configured contact form and email plugin. The form is submitted successfully and emails are sent.

The problem is that the redirection does not go to the modular page (displaying modular subpages menu). Instead, it displays the menu 'Modular Page' which is the name of the modular page and not its subpages.

If you go to the home page (/) of the site it shows this:

![image](https://user-images.githubusercontent.com/7671709/139652103-3a862ac0-29fb-4c64-9820-f3e17c858604.png)

But when you submit the contact form, the response loads the below page (/). As you see the menu is different and not contain the modular subpages.

![image](https://user-images.githubusercontent.com/7671709/139652242-b766c567-cdd7-4525-944c-75e1700c5054.png)

Pages in my admin panel are configured like this.

![image](https://user-images.githubusercontent.com/7671709/139652426-746f6276-dce6-4669-8a8b-189542ce1ba3.png)

And this is contact.md page

```
---
title: 'Contact Us'
subtitle: 'Find out more information'
section_classes: 'bg-primary-darker text-primary-lighter py-8 md:py-24'
title_text: light
form:
    name: contact
    action: '#contact'
    inline_errors: true
    fields:
        name:
            label: Name
            display_label: false
            placeholder: 'Your full name'
            autocomplete: 'on'
            type: text
            validate:
                required: true
        email:
            label: Email
            display_label: false
            placeholder: 'Your email address'
            type: email
            validate:
                required: true
        phone:
            label: Phone
            display_label: false
            placeholder: 'Your phone number (optional)'
            type: text
        message:
            label: Message
            display_label: false
            placeholder: 'Your message'
            type: textarea
            rows: 4
            validate:
                required: true
    buttons:
        submit:
            type: submit
            classes: 'no-default-style text-white bg-gray-700 hover:bg-primary'
            value: 'Submit Form'
    process:
        captcha: false
        save:
            fileprefix: contact-
            dateformat: Ymd-His-u
            extension: txt
            body: '{% include ''forms/data.txt.twig'' %}'
        email:
            from: '{{ config.plugins.email.from }}'
            to:
                - '{{ config.plugins.email.from }}'
                - '{{ form.value.email }}'
            subject: '[Site Contact Form] {{ form.value.name|e }}'
            body: '{% include ''forms/data.html.twig'' %}'
        display: /home/_contact/thankyou
        message: '<b>Thanks!</b> We''ve received your enquiry and will get back to you very soon...'
        reset: false
---

We would **love** to help you out with any question you may have.  Feel free to ask us anything and everything!
```

Feel free to test here.
https://test.codefuente.com

Any solution for this?
