### ISSUE TITLE
[nextgen-editor] Support for multiple instances

### ISSUE THREAD

**Issue by fdruide** [getgrav/grav-premium-issues#18]
We have some blueprints with multiple markdown editor. Sadly with nextgen-editor, only one is showing up. The other is never loaded.

<img width="600" alt="multiple-editors" src="https://user-images.githubusercontent.com/32466736/105221421-150da500-5b27-11eb-8d80-a67cb10086b3.png">

I did a quick test in textarea.js by looping on all textareas and it seemed to work fine. At least for loading and saving. However, it breaks some stuff such as the words counter layout or other plugins (page-inject and shortcode-core) where it expects only one instance (window.nextgenEditor.editor).

Would it be possible to support multiple instances?

Tested with a clean install :
- Grav core + Admin (v1.7.0)
- NextGen Content Editor (v1.0.3)

Here is a simplified blueprint to test multiple editors :

```
extends@: default

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          fields:
            header.summary:
              type: Markdown
              label: Summary
            content:
              type: Markdown
              label: Content
            header.media_order:
              unset@: true
```

Thank you for your time!

**Comment by w00fz** [comment]
Adding support for multiple NextGen editors is in our priority list for the next release. The way your blueprint is setup is how it will work exactly, I think i will probably also add an alias so it can be specified as `type: nextgen-editor` as well, which is less confusing.

As you noticed this is not far off but there are a few edge cases that require development to ensure its full compatibility.

**Comment by fdruide** [comment]
Thank you for you quick feedback. I'm glad it's in the list. I’m looking forward to it. 👍 

I also like the idea of the alias `type: nextgen-editor`.

**Comment by w00fz** [comment]
Support for multiple instances is now available with v1.1.0!

Cheers.

**Comment by fdruide** [comment]
Thank you so much, @w00fz. I can't wait to try it out!

**Comment by w00fz** [comment]
Make sure you update also Page Inject and Shortcode Core, it was a big change involving all potential dependencies such as those!

**Comment by christophdoering** [comment]
Is there a tutorial on how to insert multiple instances? Or an example .yaml

**Comment by w00fz** [comment]
The example @fdruide has is still valid. I haven’t added a `nextgen-editor` field but probably should do so.

```yaml
header.summary:
  type: markdown
  label: Summary
```
