### ISSUE TITLE
[form-captcha] captcha not working in contact form

### ISSUE THREAD

**Issue by rfvallina** [getgrav/grav-premium-issues#185]
Hello,
I enabled captcha verification in form plugin. I tried v2 and v3, but none is working.

- form plugin settings
```

recaptcha:
  version: '3'
  theme: light
  site_key: 6Le1tT4d...
  secret_key: 6Le1tT4d...
```

- page settings

```
process:
        captcha: true
```

When I click submit it shows error message
_reCAPTCHA bot protection has identified this form submission is problematic_

![image](https://user-images.githubusercontent.com/7671709/142256735-6d458649-2105-4958-9e7f-d7af8aed2523.png)
