### ISSUE TITLE
[algolia-pro] input[type="search"] appearance

### ISSUE THREAD

**Issue by hotdoy** [getgrav/grav-premium-issues#196]
I had some occurrence of `input type="search"` appearance going bonker and showing the default blue `X`.
(I think you have a reset in learn.getgrav).

Anyways, I added this to fix it.

```
[data-algolia-pro] input[type="search"] {
    -webkit-appearance: textfield;
}

[data-algolia-pro] input[type="search"]::-webkit-search-decoration,
[data-algolia-pro] input[type="search"]::-webkit-search-cancel-button,
[data-algolia-pro] input[type="search"]::-webkit-search-results-button,
[data-algolia-pro] input[type="search"]::-webkit-search-results-decoration { 
    display: none; 
}
```

**Comment by w00fz** [comment]
Thanks for this, I just realized about it last night on my iPhone and was going to take a look at it today!

**Comment by w00fz** [comment]
I had to change to:

```css
input[type="search"] {
    -webkit-appearance: initial;

    &::-webkit-search-decoration,
    &::-webkit-search-cancel-button,
    &::-webkit-search-results-button,
    &::-webkit-search-results-decoration {
        display: none;
    }
}
```

Because with appearance as textfield didnt look right in dark mode. Can you confirm this still works fine for you?
