### ISSUE TITLE
[typhoon] Feature suggestion: add a footer columns section / more custom items

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#207]
Hello,

This suggestion also has in mind the multilingual footer page capability.

### Suggestion:

I would like to suggest adding a new footer section to Typhoon: **multi-column footer**.
- The user select number of columns (or make it auto-detect based on the number of iterations of field lists).
- Then using a list type field, the user can set as many iterations of fields he wants for what he wants to display.

I would suggest the **possible items to be added** to be like:
- Markdown (so to display text, an image, etc.)
- Menu link (as possible in Menu Links current section).
- Social link (as possible in Social Links section)
- Custom social link: the user can manually specify the “MyBrand__brands: My Brand” text he wants to add social links that are not by default in the drop down box. No customization required.

**So the footer twig page could simply**:
- Look if a list of fields is defined so to add a “column” section in the footer page.
- Look at the number of “field lists” and make as many columns.
- Loop all fields in these lists and print them one after the other, whatever their types.

Then, the bottom copyright could stay there.

So basically, a list of list of fields. If one list is defined, then, columns.

### Example:

1. Actual Typhoon footer menu links / social links section.

2. New column section.

[columns, if defined, enabled (or set number of them)
  [column 1: [markdown for small title 1, link item] ]
  [column 2: [markdown for small title 2, link, link, link, link] ]
  [column 3: [markdown for small title 3, social, social, social__brand: My Social, markdown for small title 4, link, link] ]
]

3. Copyright (as actually, with the possibility to have it centred).

#### Output:

`
[ actual menu links at left]                             [ actual social icons ]

        Small title 1        Small title 2        Small title 3
        link item            link                 social
                             link                 social
                             link                 My Social
                             link                 Small title 4
                                                  link
                                                  link

                               Copyright © Centred
`

Thank you for your consideration.
Kind regards.

**Comment by rhukster** [comment]
When i build a site with Typhoon, i typically just redo the footer twig to customize it for the design.  It's very easy to setup those kinds of text/links in site.yaml, and then just pull those down dynamically and add them to the footer.

Something like:

`site.yaml`:
```
footer:
  menu:
    -
      title: Company
      items:
        - text: Pricing
          link: '/pricing'
        - text: Testimonials
          link: '#'
        - text: About us
          link: '/about'
        - text: Blog
          link: '/blog'
        - text: Contact us
          link: '/contact-us'
    -
      title: Support
      items:
        - text: Help center
          link: '#'
        - text: Terms of service
          link: '/terms'
        - text: Privacy policy
          link: '/privacy-policy'
        - text: Acceptable Use Policy
          link: '/aup'
        - text: Service Level Agreement
          link: '/sla'
```

`partials/footer.yaml`:
```
...
        {% for footer_menu in site.footer.menu %}
        <div class="flex-1">
          <h4 class="text-xl font-medium text-gray-100 mb-6">{{ footer_menu.title }}</h4>
          <ul>
            {% for item in footer_menu.items %}
            <li class="mb-4 hover:text-gray-200"><a href="{{ url(item.link) }}">{{ item.text }}</a></li>
            {% endfor %}
          </ul>
        </div>
        {% endfor %}
...
```

It's really not possible to support everything in Typhoon out-of-the-box, or it ends up being bulky and ungainly.  It's really intended to be a jumping-off-point, and a base for theme development.
