### ISSUE TITLE
[typhoon] Suggestion: option to display or not secondary menu

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#225]
Hello,

I would like to suggest another menu option in Typhoon: **Display secondary menu [ON/OFF]**.

**blocks/base.html.twig line 5:**
`    {% set secondary_menu = theme_var('menu.secondary_menu') ? theme_secondary_menu(page) %}`

**blueprints.yaml** after option `menu.primary_menu_levels` (about line 171):

```
                menu.secondary_menu:
                  type: toggle
                  label: 'Display secondary menu'
                  help: 'If the secondary menu should be displayed on the left in blog and post pages.'
                  highlight: 1
                  default: 1
                  options:
                    1: PLUGIN_ADMIN.YES
                    0: PLUGIN_ADMIN.NO
                  validate:
                    type: bool
```

Kind regards.
