### ISSUE TITLE
[algolia-pro] Preview/Snippets Not Appearing

### ISSUE THREAD

**Issue by thekenshow** [getgrav/grav-premium-issues#282]
I'm not getting snippets for my algolia-crawl-pages index, just a list of page titles. 

![Screen Shot 2022-05-02 at 4 21 42 PM](https://user-images.githubusercontent.com/998832/166444048-96ad9c6c-ada9-483d-94c3-7d8320e3cd45.png)

When I test it on Algolia (second image), i see a content section with highlighted matches:

![Screen_Shot_2022-04-29_at_1 00 04_PM](https://user-images.githubusercontent.com/998832/166444837-5260fa5f-7ed0-4525-a621-858d28a88606.png)

Snippets do appear in CLI:

![Screen Shot 2022-05-03 at 7 24 32 AM](https://user-images.githubusercontent.com/998832/166444680-8a26cd21-470c-470b-81d0-5557a9cf5cd0.png)

The inspector shows nothing hidden in HTML:

![Screen_Shot_2022-04-29_at_3 26 12_PM](https://user-images.githubusercontent.com/998832/166445033-4edd4ea2-e1ec-41f2-912a-21ad4d07f2fe.png)

And the Console shows no related errors:

![Screen Shot 2022-05-02 at 4 20 55 PM](https://user-images.githubusercontent.com/998832/166445126-59fe66b7-7531-472f-8f6f-c6596eff355a.png)

I can provide a zipped user folder if that helps to reproduce this.

**Comment by rhukster** [comment]
Ok sorry for taking so long with this, but I looked into it yesterday and i kept running into minor issues (specifically with crawl) that kept me busy all day fixing.

I've now released a version `1.0.6` which should be available within the hour.  This contains various minor fixes.  Some of which may or may not help your issue.  However, while trying to recreate the issue I did discover the combination of things that were missing in the default `crawl` configuration that might of caused yours.

Specifically the front end config needed to be in the right place and have preview enabled:

`aloglia-pro.yaml`:
```
crawl:
...
  interface:
  ...
     preview:
       enabled: true
       toc: true
...
```

Even after that I got the title showing, but no content summary.. That was because crawl also had another bit missing:

`aloglia-pro.yaml`:
```
crawl:
...
  interface:
  ...
     search_params:
       hitsPerPage: 20
       distinct: true
       snippetEllipsisText: '…'
       attributesToSnippet: ['summary:50', 'content:50']
...
```

Specifically the `attributesToSnippet` needed to contain `summary:50`

I suggest updating to 1.0.6 as there are some important 'crawl' things fixed that will definitely impact you, but I think your underlying issue is this configuration.

**Comment by thekenshow** [comment]
Thanks - I'll install 1.06 as soon as it's available, confirm the yaml changes above, and let you know what happens.

**Comment by thekenshow** [comment]
Updated, applied changes noted above. re-indexed, cleared cache, still the same behaviour I originally described. 

Your suggestions above had a different location for the search_params: section. You had:

```
crawl:
...
  interface:
  ...
     search_params:
       hitsPerPage: 20
       distinct: true
       snippetEllipsisText: '…'
       attributesToSnippet: ['summary:50', 'content:50']
...

But my config was:

```
crawl:
...
    search_params:
      hitsPerPage: 20
      distinct: true
      snippetEllipsisText: …
      attributesToSnippet:
        - 'summary:50'
        - 'content:50'
     ...
  interface:
  ...
...

I tried all combinations of the syntax and locations:

- Moving search_params: under interface:
- Putting quotes around the snippetEllipsisText: value
- Using the [''] format for attributesToSnippet value:

Nothing made any difference. 

Note that this site is PHP 7.3.33, in case that's a possible problem. 

I can send a zipped user folder via discord DM.
