### ISSUE TITLE
[seo-magic] Disable meta image fallback

### ISSUE THREAD

**Issue by blizam** [getgrav/grav-premium-issues#368]
In most cases I would rather no meta image be output if one isn't found via the selected method, or perhaps a simple fallback to a global image (logo/brand, etc).

Presently I have pages falling back to some default Grav image I can't even find: 

https://imgur.com/a/CRApZCM

**Comment by rhukster** [comment]
I shall investigate this possibility also.

**Comment by rhukster** [comment]
BTW, that image is set in the SEO-Magic plugin configuration:

```yaml
images:
  ...
  default_image: https://getgrav.org/user/pages/images/grav-homepage.jpg
```
