### ISSUE TITLE
[seo-magic] Image falling back to Webshot Error image instead of Default image

### ISSUE THREAD

**Issue by blizam** [getgrav/grav-premium-issues#376]
I have
```
images:
  type: media_first
  webshot_url: false
  default_image: 'https://www.domain.com/path/to/image.png'
```
I tried webshot_url: '' as well

defined in my plugin config. Instead of falling back to my default image it's falling back to this when no images are present in the page folder:

![image](https://github.com/getgrav/grav-premium-issues/assets/8940155/1979ea42-d2ce-4623-a57d-c80139fcf1c9)

How can I just disable webshot entirely from being an option and/or ensure a default image is served if there's no images in the page folder?
