### ISSUE TITLE
Menu inside or above Hero

### ISSUE THREAD

**Issue by EvgenyADE** [getgrav/grav-premium-issues#405]
Hi

Could you please help, I have the menu of the site in general above Hero, as it is in this example: https://demo.getgrav.org/typhoon/rockets/design

But on modular page it is inside Hero, as here: 
and inside the Hero like this: https://demo.getgrav.org/typhoon/rockets/history

I cannot find the setting for switching between these options.

**Comment by rhukster** [comment]
All you need to do is set the `header_bar` background to `transparent`.  

If you look in the page file (`default.md`) for the `user/pages/02.history/` page.  You will see:

```yaml
---
title: 'Rocket History'
menu: History
header_bar:
    background: transparent
    text: dark
...
```

So the background is `transparent` (on top of the hero), and the text option is set to 'dark' which means that it's suitable for 'dark' background, ie, the text is actually lighter.
