### ISSUE TITLE
[typhoon] Last.fm in Social links

### ISSUE THREAD

**Issue by EvgenyADE** [getgrav/grav-premium-issues#406]
Hi
Is it possible to add Last.fm to the social links?

**Comment by rhukster** [comment]
So i've decided rather than just adding every single social network into the CSS and dropdown, a better solution is to provide custom fields.  This will be in the next Typhoon release and to get lastfm to look decent you would have:

```
    -
      network: custom                                               # Social icon for network (choose custom to add your own)
      custom_network: Last FM                                       # Custom network name
      custom_icon: 'tabler/brand-lastfm.svg'                        # Custom icon (svg_icons style format)
      custom_colors: 'bg-red-500 text-white'                        # Custom icon colors in the format of 'bg-xxx text-xxx' (optional);
      link: https://lastfm.com/getgrav                              # External URL for network
      newtab: true                                                  # Open in new tab
```

**Comment by aleclerc7** [comment]
Nice improvement! Thank you!

**Comment by thespad** [comment]
Whatever I try I can't get the custom network to display (obviously, have updated to 2.4.5). It adds the anchor to the page footer, but not the icon. I've tried to keep it as simple as possible:
```yaml
    -
      network: custom
      custom:
         network: Mastodon
         icon: 'user/assets/lsio/brand-mastodon.svg'
      link: 'https://mastodon.linuxserver.io/@linuxserver'
```
Tried a few different locations for the icon but it doesn't seem to make a difference, the page just shows an empty anchor:
```html
<a href="https://mastodon.linuxserver.io/@linuxserver" aria-label="custom" class="text-custom  hover:filter hover:brightness-110 transition duration-300">
              
            </a>
```
