### ISSUE TITLE
[typhoon] Ajax Submission using modular template

### ISSUE THREAD

**Issue by lic0san** [getgrav/grav-premium-issues#427]
I'm not sure if it's an actual Typhoon issue, or a misconfiguration form my side, but I have difficulties to use the new Ajax Submission mode on the contact form, using a pretty strandard Typhoon modular template. Adding the "xhr_submit: true" line into ./blueprints/modular/contact.yaml (according to [documentation](https://learn.getgrav.org/17/forms/forms/how-to-ajax-submission)) seems to have no effect at all. Adding it to the form's frontmatter instead does have an effect, but the the validation process then replaces the whole modular page by the raw form only, hence with no theming : 
![image](https://github.com/getgrav/grav-premium-issues/assets/120644765/dd855c01-ad9a-4074-bb43-5c80e6854926)

In case it might be related, I am using theme inheritance to customize Typhoon (appears to work well beyond that).

**Comment by rhukster** [comment]
I was able to have a single modular form with out any issues in Typhoon. However, I did have an issue when i tried to add another modular form in the same page. I was able to replicate your issue.  Are you doing this?

BTW, this appears to be an issue with Form plugin and is not specific to Typhoon.

**Comment by lic0san** [comment]
No, I actually only use one modular form in the page...

Here is the frontmatter if it helps :

```
title: Contact
form:
    xhr_submit: true
    name: contact
    action: '#contact'
    inline_errors: true
    fields:
        name:
            label: Name
            display_label: false
            placeholder: 'Votre nom *'
            autocomplete: 'on'
            type: text
            validate:
                required: true
        email:
            label: Email
            display_label: false
            placeholder: 'Votre adresse de courriel *'
            type: email
            validate:
                required: true
        phone:
            label: Phone
            display_label: false
            placeholder: 'Votre numéro de téléphone'
            type: text
        message:
            label: Message
            display_label: false
            placeholder: 'Votre message *'
            type: textarea
            rows: 4
            validate:
                required: true
        human:
            label: 'Êtes-vous humain ?'
            type: text
            placeholder: 'Votre réponse en trois lettres'
            validate:
                type: text
                required: true
                pattern: '(?i)oui'
                message: 'Les trois lettres attendues sont des voyelles.'
    buttons:
        submit:
            type: submit
            classes: 'no-default-style text-white bg-gray-700 hover:bg-primary'
            value: 'Envoyer le message'
    process:
        ip:
            value: 'User IP Address'
        save:
            fileprefix: contact-
            dateformat: Ymd-His-u
            extension: txt
            body: '{% include ''forms/data.txt.twig'' %}'
        email:
            metadata:
                Originating-IP: '{{ uri.ip() }}'
                Human: '{{ browser.ishuman() }}'
            from: '{{ form.value.name|e }} <{{ form.value.email }}>'
            subject: '[ACP] {{ form.value.name|e }}'
            body: '{% include ''forms/data.html.twig'' %}'
        message: 'Votre message est bien envoyé !'
        reset: true
section_classes: 'bg-gray-100 dark:bg-gray-800 py-8 md:py-24'
```

Side remark : I don't want to use Google or Cloudflare captchas, so I first tried to use the "Basic-Captcha" test... And I still received *a lot* off spam : robots apparently didn't break a sweat on it. Then, I downgraded it to a dead-simple human verification test with an obvious regexp (just asking "are you human?" and expecting the user to answer "yes" in french) : this is apparently a much greater challenge to the robots, and not a single spam broke through since that day !
