### ISSUE TITLE
[site-toolbox] Does premium plugin warm cache work with login plugin

### ISSUE THREAD

**Issue by Japhys** [getgrav/grav-premium-issues#441]
Hi,

I would like to purchase the warm cache plugin but have some questions.

I have a single instagram like page with a 1000+ high quality images. I am actually quite surprised how well this works, they load very very fast still. There is only one problem. When I do an CMS update, cache is emptied. When loading the photo page afterwards it runs out of memory a couple of times before the page finally loads. In the admin panel it also takes forever for the page with attachments thumbnails to load. Now I can make sure the cache doesn’t get deleted by renaming the folder during update but that is a hassle.

My photo page is behind a login. 

My questions:

- will this work behind a login?
- if it runs out of memory, will this halt the caching process altoghether?

Any other ideas how to handle this are very welcome as well.

**Info setup**

VPS 4 cores | 8 GB
Ubuntu 22.04 / Docker / Ngninx proxy manager

Grav v1.7.46 - Admin v1.10.46
Login plugin  v3.7.9

```
version: "2.1"
services:
  grav:
    image: lscr.io/linuxserver/grav:latest
    container_name: grav
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /srv/grav/config:/config
    ports:
      - 7400:80
    restart: unless-stopped

```
