### ISSUE TITLE
Typhoon --> child template --> Twig \ Error \ RuntimeError

### ISSUE THREAD

**Issue by anico-sy** [getgrav/grav-premium-issues#50]
Hi

I created a Custom Theme with the Typhoon-Theme (licenced)
According to:
https://getgrav.org/premium/typhoon/docs#create-a-custom-theme-from-typhoon
activated it in the admin tool
Delete cache in the admin tool

now I have a
Twig \ Error \ RuntimeError
An exception has been thrown during the rendering of a template ("HEX
color needs to be 6 or 3 digits long").

see [https://www.anico.ch/issue/](https://www.anico.ch/issue/)

Anybody knows what is the reason for this issue?

Thanks and best regards
Bernhard

**Comment by w00fz** [comment]
Hi @anico-sy,

The error seems to indicate you have a wrong hex color defined for your primary color, what’s the value you are using?

**Comment by anico-sy** [comment]
Hi 

Screenshot before change:
[https://www.anico.ch/issue/forum/primary_color.png](https://www.anico.ch/issue/forum/primary_color.png)
in the template typhoon I changed the primary-color to
#137df5
in the child theme, I do not see any color definition in the yaml-files

Where can be a primary color?

Thanks in advance
Bernhard

**Comment by anico-sy** [comment]
or do I have to copy the 
typhoon.yaml
to the child theme and rename it?

**Comment by anico-sy** [comment]
OK.... I see already the problem. 
There is file-content missing in the child.

I copied the typhoon.yaml
https://www.anico.ch/issue/
to the child and than the HEX error is gone.

Question: Which files I have to copy from the typhoon to the child?


Thanks 
Bernhard

**Comment by rhukster** [comment]
That is actually normal behavior for child themes.  The configuration YAML is critical for the theme and not inherited. It should be copied to the cold theme per the documentation: https://learn.getgrav.org/17/themes/customization#inheriting-using-the-cli

**Comment by anico-sy** [comment]
Hi
I made all the steps:
Inheriting using the CLI
https://learn.getgrav.org/17/themes/customization#inheriting-using-the-cli

then I got the
ERROR: default.html.twig template not found for page: /
on page https://www.anico.ch/issue/

than
I copied  default.html.twig from thypoon to
/user/themes/anico/templates/default.html.twig

but than I got the error
"partials/base.html.twig is missing.

I think, there is still a misfunction of the inherit function. 
I understand, that Inheriting should get the missing files from the Typhoon-template.

Do you have an idea what is the issue?

**Comment by rhukster** [comment]
It sounds like your theme didn’t get setup properly with inheritance.  If you used the devtools approach everything should just work out of the box. It does for me in my test child theme.  Perhaps you can zip up your child theme and attach it and I can take a look?

**Comment by anico-sy** [comment]
Hi
below the link to the child-theme
https://www.anico.ch/issue/user/themes/anico.zip

Thanks!

**Comment by rhukster** [comment]
Ok I don't think you used the `bin/plugin devtools` command because your files are incorrect.  you have a `_anico.yaml` with the stream information but this should be at the top of your `anico.yaml` file:

```yaml
treams:
 schemes:
   theme:
     type: ReadOnlyStream
     prefixes:
       '':
         - user/themes/anico
         - user/themes/typhoon

enabled: true                                                       # Enable the theme
production: false                                                   # production | development (compiled or development version of css)
append_site_title: true                                             # Append Site Title to HTML Title
custom_logo:                                                        # Will be used instead of default Grav logo
custom_logo_strip_svg_style: false    
....
```

Then it should work
