### ISSUE TITLE
Thumbnails Grave Lightbox Gallery Premium

### ISSUE THREAD

**Issue by mario548** [getgrav/grav-premium-issues#62]
Hello
i have the Grav Lightbox Gallery and follow the example "Gallery Lightbox with Shortcodes" but now the thumbnails are vertical.

This is my code for the Gallery:
```
[lightbox image="Kathrin_und_Dieter-03.jpg" gallery="gallery1" class="inline-block" desc="Test"]
![Red DBS - 1](Kathrin_und_Dieter-03.jpg?cropZoom=200,200)
[/lightbox]

[lightbox image="Kathrin_und_Dieter-09.jpg" gallery="gallery1" class="inline-block" desc="Test"]
![Red DBS - 2](Kathrin_und_Dieter-09.jpg?cropZoom=200,200)
[/lightbox]

[lightbox image="Kathrin_und_Dieter-12.jpg" gallery="gallery1" class="inline-block" desc="Test"]
![Red DBS - 3](Kathrin_und_Dieter-12.jpg?cropZoom=200,200)
[/lightbox]

[lightbox image="Kathrin_und_Dieter-14.jpg" gallery="gallery1" class="inline-block" desc="Test"]
![Red DBS - 4](Kathrin_und_Dieter-14.jpg?cropZoom=200,200)
[/lightbox]
```
and how it's looks like.
![Bildschirmfoto von 2021-03-04 19-51-45](https://user-images.githubusercontent.com/72807257/110016977-f99cd900-7d25-11eb-8349-af8196638fa0.png)

Thank you very much
Mario

**Comment by rhukster** [comment]
As this is something that is theme specific, we've got documentation on how to set up a grid gallery like the examples (which use Typhoon theme):

https://getgrav.org/premium/lightbox-gallery/docs#displaying-a-gallery-of-thumbnails

This should help you create the required layout in pretty much any theme.

**Comment by mario548** [comment]
Thank you for the quick answer.
I add this gallery.html.twig at "user/themes/antimatter/templates/partials".
I created a gallery.md for testing, but it don't work and i add this line "{% do lightbox_gallery.addAssets() %}" at "user/themes/antimatter/templates/default.html.twig" but it don't work on my default testing site.

This is the full code of the default.de.md site, when it is finished i won't some text then a gallery then text then a gallery......
```
  GNU nano 3.2                                              default.de.md                                                          

---
title: test
published: true
metadata:
    Hochzeit: 'Hochzeit, Ausee, Kahling Bergergut, Oberösterreich, Hochzeitsfotografie'
body_classes: header-animated
visible: false
hero_classes: hero-small
hero_image: IMG_87231.jpg
---

[lightbox image="Kathrin_und_Dieter-03.jpg" gallery="gallery1" class="inline-block" desc="Test"]
![Red DBS - 1](Kathrin_und_Dieter-03.jpg?cropZoom=200,200)
[/lightbox]

[lightbox image="Kathrin_und_Dieter-09.jpg" gallery="gallery1" class="inline-block" desc="Test"]
![Red DBS - 2](Kathrin_und_Dieter-09.jpg?cropZoom=200,200)
[/lightbox]

[lightbox image="Kathrin_und_Dieter-12.jpg" gallery="gallery1" class="inline-block" desc="Test"]
![Red DBS - 3](Kathrin_und_Dieter-12.jpg?cropZoom=200,200)
[/lightbox]

[lightbox image="Kathrin_und_Dieter-14.jpg" gallery="gallery1" class="inline-block" desc="Test"]
![Red DBS - 4](Kathrin_und_Dieter-14.jpg?cropZoom=200,200)
[/lightbox]
```

**Comment by rhukster** [comment]
Your use of the shortcode in your content is fine, but it has no HTML structure. If you inspect your output, you simply have a series of `<a></a>` tags with `<img />` tags inside them.  The example I provided is assuming you have the custom frontmatter setup as shown in the page example in the docs, eg:

```yaml
gallery:
    thumb:
        width: 400
        height: 300
    items:
        -
            title: 'Climbing Hilly Peaks'
            image: david-marcu-78A265wPiO4-unsplash.jpg
            desc: 'Etiam pretium elit vitae eros fringilla, vel gravida augue eleifend. Ut convallis, lacus non eleifend maximus, turpis odio mollis enim, ac malesuada quam leo ut augue. Quisque mollis urna ac ex varius, vel faucibus enim lacinia. Aenean a lorem consectetur, pulvinar sem nec, ultrices quam. Ut scelerisque, nibh vitae bibendum tincidunt, urna nisl viverra nulla, in mollis erat purus a mauris'
        -
            title: 'Golden Sand Dunes'
            image: sergey-pesterev-_VqyrvQi6do-unsplash.jpg
            ...
```

This is the data that is used by the partial.  If you want to use the shortcodes alone, you can make use of the a custom div shortcode wrapper, and then some classes for example:

```
[div class="lightbox-gallery"]
[lightbox image="Kathrin_und_Dieter-03.jpg" gallery="gallery1" class="lightbox-item" desc="Test"]
![Red DBS - 1](Kathrin_und_Dieter-03.jpg?cropZoom=200,200)
[/lightbox]

[lightbox image="Kathrin_und_Dieter-09.jpg" gallery="gallery1" class="lightbox-item" desc="Test"]
![Red DBS - 2](Kathrin_und_Dieter-09.jpg?cropZoom=200,200)
[/lightbox]

[lightbox image="Kathrin_und_Dieter-12.jpg" gallery="gallery1" class="lightbox-item" desc="Test"]
![Red DBS - 3](Kathrin_und_Dieter-12.jpg?cropZoom=200,200)
[/lightbox]

[lightbox image="Kathrin_und_Dieter-14.jpg" gallery="gallery1" class="lightbox-item" desc="Test"]
![Red DBS - 4](Kathrin_und_Dieter-14.jpg?cropZoom=200,200)
[/lightbox]
[/div]
```

Then some CSS to provide some flexbox classes:

```css
.lightbox-gallery {
  display: flex;
  flex-wrap: wrap;
  margin: 0 -10px;
}

.lightbox-gallery .lightbox-item {
  width: 50%;
  padding: 0 10px;
  margin-bottom: 20px;
}

.lightbox-gallery img {
  display: block;
  border-radius: 5px;
  transition: all .2s ease-in-out;
}

.lightbox-gallery img:hover {
  filter: brightness(60%);
  transform: scale(1.05);
}
```

Completely untested, but should give you a general direction to work with.

**Comment by mario548** [comment]
Thank you for your Help, i found my mistake in the shortcode. I test this with the div class and the css before i post here and i forget the end form the style ([/style]). Beginner mistake because I don't work much with css.

But I have some error in the Frontmatter setup.
I add the gallery.html.twig at "user/themes/antimatter/templates/partials" and create some test site.

```
gallery.de.md                                                                                                  

---
title: 'Powerful Gallery'
subtitle: 'Exploring the globe...'
gallery:
        thumb:
                width: 400
                height: 300
        items:
        -
                title: 'Climbing Hilly Peaks'
                image: Kathrin_und_Dieter-03.jpg
                desc: 'test'
        -
                title: 'Golden Sand Dunes'
                image: Kathrin_und_Dieter-09.jpg
                desc: 'test'
---
Test 123456
```

The Result:
![Bildschirmfoto von 2021-03-04 22-59-38](https://user-images.githubusercontent.com/72807257/110036663-a2a2fe00-7d3d-11eb-8297-0854106e2dbf.png)

Thank you for help.

**Comment by rhukster** [comment]
Items should be indented like this:

```yaml
        items:
          -
                title: 'Climbing Hilly Peaks'
                image: Kathrin_und_Dieter-03.jpg
                desc: 'test'
          -
                title: 'Golden Sand Dunes'
                image: Kathrin_und_Dieter-09.jpg
                desc: 'test'
```
