### ISSUE TITLE
[SEO-MAGIC] Pages won't save // Few critical errors

### ISSUE THREAD

**Issue by cur1ou5soul** [getgrav/grav-premium-issues#87]
I Can't save a Page or delete all SEO magic information. 

System 
Dedicated Server Nginx

Grav 1.7.10.
SeoMagic 1.0.3

![image](https://user-images.githubusercontent.com/57013347/114901082-bcdbfb80-9e14-11eb-8868-265723f8d566.png)

If I disable the plugin the error doesn't pop up. 

`Too few arguments to function Grav\Plugin\SEOMagic\SEOGenerator::removeSEOData(), 0 passed in /var/www/html/siskaselement.com/user/plugins/seo-magic/seo-magic.php on line 151 and exactly 1 expected`

**Comment by rhukster** [comment]
Is it possible to get a copy of a page (the .md file) that is causing this issue, then I can see what's tripping things up?

**Comment by cur1ou5soul** [comment]
I dug a little deeper and found more or less a way to nail the error down

# I've set up my site to be multi Site
# I've Domains ending in .com and .de
# I redirected the /de to .de and /en .com 

That's the .en.md
```

---
title: 'Guiding Light [Around the World]'
feed:
    limit: 10
media_order: Cover_1500_sm.jpg
shop: d
spotify: d
published: true
visible: false
seo-magic:
    images:
        image_name: Cover_1500_sm.jpg
---

```
